"""
PHASE 8: Visualization of Continuous Hill-Based Circuit Results
================================================================
Standalone script to generate visualizations from Phase 8 results.

This reads the CSV files generated by soft_logic_search.py and creates
publication-quality figures comparing P_star distributions.
"""

import numpy as np
import pandas as pd
import scanpy as sc
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
from scipy.sparse import issparse

# Load constant
ALPHA = 50.0
GAMMA = 0.1
ALPHA_OVER_GAMMA = ALPHA / GAMMA
LETHAL_THRESHOLD = 150.0
HILL_N = 2.0

print("=" * 80)
print("PHASE 8: VISUALIZATION - Continuous Hill-Based Circuit Analysis")
print("=" * 80)

# Load data
print("\n[1/3] Loading raw data and results...")
adata = sc.read_h5ad('LUAD.h5ad')
adata.obs['is_cancer'] = (adata.obs['author_cell_type_level_1'] == 'Epithelial').astype(int)

# Subsample
np.random.seed(42)
sc.pp.subsample(adata, n_obs=5000, random_state=42)
sc.pp.filter_genes(adata, min_cells=500)

X_matrix = adata.X.toarray() if issparse(adata.X) else adata.X
X_matrix = np.asarray(X_matrix, dtype=np.float32)

y_cancer = adata.obs['is_cancer'].values
cancer_mask = (y_cancer == 1)
healthy_mask = (y_cancer == 0)
gene_names = np.array(adata.var_names.tolist())

# Load thresholds
p_thr_all = np.percentile(X_matrix[healthy_mask, :], 95, axis=0) + 0.1
r_thr_all = np.percentile(X_matrix[cancer_mask, :], 95, axis=0) + 0.1

print(f"   Cells: {adata.n_obs} (Cancer: {np.sum(cancer_mask)}, Healthy: {np.sum(healthy_mask)})")
print(f"   Genes: {adata.n_vars}")

# Load Phase 8 results
results_df = pd.read_csv('results/soft_logic_search_results_20260406_005101.csv')
print(f"   Phase 8 results loaded: {len(results_df)} circuits")

top5 = results_df.head(5)

print("\n[2/3] Computing P_star for top 5 circuits...")

sns.set_style("whitegrid")
plt.rcParams['figure.dpi'] = 100

# Create main visualization
fig, axes = plt.subplots(2, 3, figsize=(18, 10))
fig.suptitle(
    "Phase 8: Continuous Hill-Based Circuit Analysis\nP_star Distributions (Steady-State Killer Protein)",
    fontsize=14, fontweight='bold', y=0.995
)

axes_flat = axes.flatten()

for plot_idx in range(6):
    ax = axes_flat[plot_idx]
    
    if plot_idx < len(top5):
        circuit = top5.iloc[plot_idx]
        
        p1_idx = int(circuit['p1_idx'])
        p2_idx = int(circuit['p2_idx'])
        r_idx = int(circuit['r_idx'])
        
        # Extract expressions
        expr_p1 = X_matrix[:, p1_idx].astype(np.float32)
        expr_p2 = X_matrix[:, p2_idx].astype(np.float32)
        expr_r = X_matrix[:, r_idx].astype(np.float32)
        
        K_p1 = p_thr_all[p1_idx]
        K_p2 = p_thr_all[p2_idx]
        K_r = r_thr_all[r_idx]
        
        # Hill functions
        H_p1 = (expr_p1 ** HILL_N) / (K_p1 ** HILL_N + expr_p1 ** HILL_N)
        H_p2 = (expr_p2 ** HILL_N) / (K_p2 ** HILL_N + expr_p2 ** HILL_N)
        H_r_inv = (K_r ** HILL_N) / (K_r ** HILL_N + expr_r ** HILL_N)
        
        # Soft OR and gate
        H_or = 1.0 - (1.0 - H_p1) * (1.0 - H_p2)
        H_inhibition = 1.0 - H_r_inv
        gate_output = H_or * H_inhibition
        P_star = ALPHA_OVER_GAMMA * gate_output
        
        # Split by cell type
        P_star_cancer = P_star[cancer_mask]
        P_star_healthy = P_star[healthy_mask]
        
        # Plot histograms
        ax.hist(P_star_cancer, bins=40, alpha=0.65, label='Cancer', color='#d62728', edgecolor='darkred', linewidth=0.5)
        ax.hist(P_star_healthy, bins=40, alpha=0.65, label='Healthy Immune', color='#1f77b4', edgecolor='darkblue', linewidth=0.5)
        
        # Threshold line
        ax.axvline(LETHAL_THRESHOLD, color='black', linestyle='--', linewidth=2.5, label=f'Lethal Threshold\n({LETHAL_THRESHOLD} nM)', zorder=10)
        
        # Statistics
        cancer_kills = np.sum(P_star_cancer > LETHAL_THRESHOLD)
        healthy_kills = np.sum(P_star_healthy > LETHAL_THRESHOLD)
        
        # Title
        ax.set_title(
            f"Rank {plot_idx + 1}: Reward = {circuit['reward']:.0f}\n"
            f"Kills {cancer_kills}/{int(circuit['cancer_kills'])} cancer | "
            f"Toxicity {healthy_kills}/{int(circuit['healthy_kills'])} healthy",
            fontsize=10, fontweight='bold', pad=8
        )
        
        ax.set_xlabel('P_star (nM)', fontsize=9)
        ax.set_ylabel('Cell Count', fontsize=9)
        ax.legend(fontsize=8.5, loc='upper right', framealpha=0.95)
        ax.grid(True, alpha=0.3)
        ax.set_xlim(left=0)
    else:
        # Empty subplot
        ax.text(0.5, 0.5, '(Reserved for future circuits)',
                ha='center', va='center', transform=ax.transAxes,
                fontsize=11, style='italic', color='gray')
        ax.set_xticks([])
        ax.set_yticks([])

plt.tight_layout()
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
viz_path = f"results/phase8_visualization_histograms_{timestamp}.png"
plt.savefig(viz_path, dpi=300, bbox_inches='tight')
print(f"✓ Saved histogram visualization: {viz_path}")
plt.close()

# Create statistics comparison plot
print("\n[3/3] Creating comparative statistics plots...")

cancer_means = []
healthy_means = []
cancer_stds = []
healthy_stds = []

for _, circuit in top5.iterrows():
    p1_idx = int(circuit['p1_idx'])
    p2_idx = int(circuit['p2_idx'])
    r_idx = int(circuit['r_idx'])
    
    expr_p1 = X_matrix[:, p1_idx].astype(np.float32)
    expr_p2 = X_matrix[:, p2_idx].astype(np.float32)
    expr_r = X_matrix[:, r_idx].astype(np.float32)
    
    K_p1 = p_thr_all[p1_idx]
    K_p2 = p_thr_all[p2_idx]
    K_r = r_thr_all[r_idx]
    
    H_p1 = (expr_p1 ** HILL_N) / (K_p1 ** HILL_N + expr_p1 ** HILL_N)
    H_p2 = (expr_p2 ** HILL_N) / (K_p2 ** HILL_N + expr_p2 ** HILL_N)
    H_r_inv = (K_r ** HILL_N) / (K_r ** HILL_N + expr_r ** HILL_N)
    
    H_or = 1.0 - (1.0 - H_p1) * (1.0 - H_p2)
    H_inhibition = 1.0 - H_r_inv
    gate_output = H_or * H_inhibition
    P_star = ALPHA_OVER_GAMMA * gate_output
    
    P_star_cancer = P_star[cancer_mask]
    P_star_healthy = P_star[healthy_mask]
    
    cancer_means.append(np.mean(P_star_cancer))
    healthy_means.append(np.mean(P_star_healthy))
    cancer_stds.append(np.std(P_star_cancer))
    healthy_stds.append(np.std(P_star_healthy))

# Create comparison figure
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle("Phase 8: P_star Statistics - Top 5 Circuits", fontsize=12, fontweight='bold')

# Plot 1: Mean comparison with error bars
ax1 = axes[0]
x = np.arange(5)
width = 0.35

ax1.bar(x - width/2, cancer_means, width, label='Cancer Mean', color='#d62728', alpha=0.8, edgecolor='darkred')
ax1.bar(x + width/2, healthy_means, width, label='Healthy Mean', color='#1f77b4', alpha=0.8, edgecolor='darkblue')
ax1.axhline(LETHAL_THRESHOLD, color='black', linestyle='--', linewidth=2, label='Lethal Threshold', zorder=5)

ax1.set_xlabel('Circuit Rank', fontsize=10)
ax1.set_ylabel('Mean P_star (nM)', fontsize=10)
ax1.set_title('Mean Killer Protein by Circuit', fontsize=10, fontweight='bold')
ax1.set_xticks(x)
ax1.set_xticklabels([f'C{i+1}' for i in range(5)])
ax1.legend(fontsize=9, loc='upper right')
ax1.grid(True, alpha=0.3, axis='y')
ax1.set_ylim(bottom=0)

# Plot 2: Efficacy vs Specificity (Pareto frontier)
ax2 = axes[1]

cancer_kill_rates = (top5['cancer_kills'].values / np.sum(cancer_mask)) * 100
healthy_toxicity_rates = (top5['healthy_kills'].values / np.sum(healthy_mask)) * 100

scatter = ax2.scatter(healthy_toxicity_rates, cancer_kill_rates, 
                     s=300, alpha=0.7, c=np.arange(5), cmap='viridis', 
                     edgecolors='black', linewidth=1.5)

for i in range(5):
    ax2.annotate(f'C{i+1}', 
                xy=(healthy_toxicity_rates[i], cancer_kill_rates[i]),
                xytext=(5, 5), textcoords='offset points', fontsize=9, fontweight='bold')

ax2.set_xlabel('Healthy Cell Toxicity (%)', fontsize=10)
ax2.set_ylabel('Cancer Cell Kill Rate (%)', fontsize=10)
ax2.set_title('Clinical Efficacy-Specificity Tradeoff', fontsize=10, fontweight='bold')
ax2.grid(True, alpha=0.3)
ax2.set_xlim(left=-1)
ax2.set_ylim(bottom=0)

plt.tight_layout()
stats_path = f"results/phase8_visualization_statistics_{timestamp}.png"
plt.savefig(stats_path, dpi=300, bbox_inches='tight')
print(f"✓ Saved statistics visualization: {stats_path}")
plt.close()

print("\n" + "=" * 80)
print("VISUALIZATION COMPLETE")
print("=" * 80)
print(f"\nGenerated visualizations:")
print(f"  1. {viz_path}")
print(f"  2. {stats_path}")
print(f"\nPhase 8 analysis complete. Ready for Phase 9: Gillespie SSA validation.")
print("=" * 80)
